//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.Score = 0D;
            this.Explored = false;
            this.PrevState = new HashSet<State>();
            this.NextState = new HashSet<State>();
        }
    
        public int Id { get; set; }
        public double Hash { get; set; }
        public double Score { get; set; }
        public bool Explored { get; set; }
    
        public virtual ICollection<State> PrevState { get; set; }
        public virtual ICollection<State> NextState { get; set; }
    }
}
