//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XO
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics;

    [DebuggerDisplay("{Hash}, {Explored}, {Score}")]
    public partial class State
    {
        public State()
        {
            this.Score = 0D;
            this.Explored = false;
            this.Actions = new HashSet<Action>();
            this.Causes = new HashSet<Action>();
        }
    
        public int Hash { get; set; }
        public double Score { get; set; }
        public bool Explored { get; set; }
    
        public virtual ICollection<Action> Actions { get; set; }
        public virtual ICollection<Action> Causes { get; set; }
    }
}
